export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_DRIVER='ADD_DRIVER';
export const EDIT_DRIVER='EDIT_DRIVER';
export const GET_DRIVER='GET_DRIVER';
export const DELETE_DRIVER='DELETE_DRIVER';
export const LOADING_DRIVER='LOADING_DRIVER'

export const ADD_CAR='ADD_CAR';
export const EDIT_CAR='EDIT_CAR';
export const GET_CAR='GET_CAR';
export const DELETE_CAR='DELETE_CAR';
export const LOADING_CAR='LOADING_CAR'

export const ADD_CARMANUFACTURER='ADD_CARMANUFACTURER';
export const EDIT_CARMANUFACTURER='EDIT_CARMANUFACTURER';
export const GET_CARMANUFACTURER='GET_CARMANUFACTURER';
export const DELETE_CARMANUFACTURER='DELETE_CARMANUFACTURER';
export const LOADING_CARMANUFACTURER='LOADING_CARMANUFACTURER'
